version: 2.1

orbs:
  node: circleci/node@4.0.0
  slack: circleci/slack@3.4.2

attachws: &attach_ws
    at: ~/project

slackmessage_e: &slackmessage_error
  channel: mystique
  fail_only: true
  webhook: https://hooks.slack.com/services/${SLACK_WEBHOOK}
  failure_message: ":disappointed: Failed! $CIRCLE_USERNAME's workflow on $CIRCLE_BRANCH at $CIRCLE_JOB. ($CIRCLE_BUILD_URL)"

slackmessage_s: &slackmessage
  channel: mystique
  webhook: https://hooks.slack.com/services/${SLACK_WEBHOOK}
  failure_message: ":disappointed: Failed! $CIRCLE_USERNAME's workflow on $CIRCLE_BRANCH at $CIRCLE_JOB. ($CIRCLE_BUILD_URL)"
  success_message: ":tada: Success! $CIRCLE_USERNAME's workflow on $CIRCLE_BRANCH at $CIRCLE_JOB! ($CIRCLE_BUILD_URL)"

jobs:
  install:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - attach_workspace:
          <<: *attach_ws
      - node/install-packages:
          pkg-manager: yarn
          cache-path: ~/project/node_modules
      - persist_to_workspace:
          root: .
          paths: [node_modules]
      - run: node --version
      - slack/status:
          <<: *slackmessage_error

  lint:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - attach_workspace:
          <<: *attach_ws
      - run:
          name: JS Lint
          command: yarn lint
      - slack/status:
          <<: *slackmessage_error

  release:
    executor:
      name: node/default
      tag: '14.15'
    steps:
      - checkout
      - attach_workspace:
          <<: *attach_ws
      - run:
          name: Semantic release
          command: yarn semantic-release
      - slack/status:
          <<: *slackmessage_error

workflows:
  cewebpack_flow:
    jobs:
      - install:
          context: aws-context
      - lint:
          context: aws-context
          requires:
            - install
      - release:
          context: aws-context
          filters:
            branches:
              only:
                - master
                - QA
          requires:
            - lint
